server:
  port: 9999

spring:
  application:
    name: navi-configserver

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ganxf/springcloudconfig.git
#          uri: https://github.com/navi1275/Java-learn.git
          timeout: 5
          default-label: master
          strict-host-key-checking: false
          username: gxf-ly2009@163.com
          password: feng2008
#          basedir: SpringCloud/config

