
kafka:
  topic: cities


spring:
  kafka:
    bootstrap-servers: 192.168.4.129:9092,192.168.4.129:9093,192.168.4.129:9094

    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: cityconsumergroup
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer